#!/usr/bin/env just --justfile

home-manager-cmd := "home-manager --extra-experimental-features 'nix-command flakes'"

# show available commands
[private]
default:
    @just --list

# link dotfiles using home-manager
link:
    {{ home-manager-cmd }} switch --flake .
