#!/usr/bin/env just --justfile

# show available commands
[private]
default:
    @just --list

# check configuration validity (dry-run)
check hostname=`hostname -s`:
    sudo nixos-rebuild dry-build --flake .#{{ hostname }}

# build a specific host configuration
build hostname=`hostname -s`:
    sudo nixos-rebuild switch --flake .#{{ hostname }}

# rebuild the current host
rebuild:
    @just build $(hostname)
